package com.newton.handler;

public enum Instruction {
  CREATE_PARKING_LOT,
  PARK,
  STATUS,
  LEAVE,
  REGISTRATION_NUMBERS_FOR_CARS_WITH_COLOUR,
  SLOT_NUMBERS_FOR_CARS_WITH_COLOUR,
  SLOT_NUMBER_FOR_REGISTRATION_NUMBER,
  HELP,
  EXIT;
}
